version: '3'

services:
  db:
    image: postgres:12
    container_name: db
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: dev
      POSTGRES_DB: devdb
    ports:
      - "54320:5432"

volumes:
  db_data:
